/**=====================================================================
 * Appirio, Inc
 * Name: BatchBUCreationManualStartCont_Test
 * Description: Test Class.
 * Created Date: Dec 08th, 2013
 * Created By:  Mohammed Irfan (Appirio)
 * 
 * Date Modified                Modified By                  Description of the update
 * Jan 30th, 2014               Jinesh Goyal(Appirio)                T-232760: Homogenize the comments
 * Mar 20th, 2014               Arpita Bose (Appirio)        T-253906: Code coverage increased
 * Apr 23rd, 2014               Arpita Bose                  Updated runTest()to increase code coverage
 =====================================================================*/

@isTest (SeeAllData = false) 
private class BatchBUCreationManualStartCont_Test {
    static testMethod void  runTest() {
      /*  //create test data
        Account acc = Test_Utils.insertAccount();
        BU_Relationship__c bu = Test_Utils.createBURelationship(acc.Id);
        insert bu;
        //start test
        Test.startTest();
        BatchBUCreationManualStartController cls = new BatchBUCreationManualStartController();
        cls.startBatch();
        String message = cls.confirmationMessage;
      //stop test  
      Test.stopTest();  
        */
    }
}