/**=====================================================================
 * Appirio, Inc
 * Name: BURelationshipCalculator_Schedule
 * Description: Schedule BURelationshipCalculator_Batch to run daily
 * Created Date: Nov 07th, 2013
 * Created By: Pankaj Mehra (Appirio) 
 * 
 * Date Modified                Modified By                  Description of the update
 * Apr 23, 2014                 Nathalie Le Guay             Commenting class
 =====================================================================*/
/*global*/public class BURelationshipCalculator_Schedule /*implements Schedulable*/ {
   /*global void execute(SchedulableContext SC) {
      BURelationshipCalculator_Batch batch = new BURelationshipCalculator_Batch(); 
      Database.executeBatch(batch, 200);
   }*/
}