/**=====================================================================
 * Appirio, Inc
 * Class Name: OpportunityPlanCompetitorTrigger_Test
 * Description: 
 * Created Date: Oct 30th, 2014
 * Created By: Arpita Bose (Appirio)
 * 
 * Date Modified                Modified By                  Description of the update       
 =====================================================================*/
@isTest
private class OpportunityPlanCompetitorTrigger_Test {

    static testMethod void myUnitTest() {
      /*  // create test data
        Account acc = Test_Utils.insertAccount();
        
        Opportunity opp = Test_Utils.insertOpportunity(acc.Id);
        
        Opportunity_Plan__c oPlan = Test_Utils.insertOpportunityPlan(false, opp.Id);
        oPlan.CurrencyIsoCode = 'USD';
        insert oPlan;
        
        Opportunity_Plan_Competitor__c opComp = new Opportunity_Plan_Competitor__c();
        opComp.Opportunity_Plan__c = oPlan.Id;
        insert opComp;
        
        Test.startTest();
        oPlan.CurrencyIsoCode = 'GBP';
        update oPlan;         
        Test.stopTest(); */
        
    }
}