/**=====================================================================
 * Appirio, Inc
 * Name: TestBUStructure
 * Description: 
 * Created Date: Nov 20th, 2013
 * Created By: Mohammed Irfan (Appirio)
 * 
 * Date Modified                Modified By                  Description of the update
 * Jan 30th, 2014                                     Jinesh Goyal(Appirio)              T-232760: Homogenize the comments
 * Mar 04th, 2014               Arpita Bose(Appirio)             T-243282: Added Constants in place of String
 =====================================================================*/

@isTest
private class TestBUStructure{

    static testMethod void testBUStructure(){
    /*Global_Settings__c custSettings = new Global_Settings__c(name=Constants.GLOBAL_SETTING,Account_Team_Member_Default_Role__c=Constants.TEAM_ROLE_ACCOUNT_MANAGER,Smart_Search_Query_Limit__c=250);
        insert custSettings;

        Account acc = new Account(Name='test');
        insert acc;
        
        BU_Relationship__c bu = new BU_Relationship__c(Account__c=acc.id);
        insert bu;

        test.startTest();
        
        PageReference BUHierarchyPage= Page.BUHierarchyPage;
        Test.setCurrentPage( BUHierarchyPage);
        ApexPages.currentPage().getParameters().put( 'id', acc.id );
    
        // Instanciate Controller
        BUStructure controller = new BUStructure();
        controller.getObjectStructure();
        controller.isLastNode(new List<String>{'1'});
       
        test.stopTest();
        */
    }

}